name: Deployment to Production
on:
  push:
    branches:
      - master
  #Get the secret auth token from Fly.io
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy_app:
    runs-on: ubuntu-20.04
    steps:
      #Make possible to use flycyl run commands
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app
        run: flyctl deploy --remote-only
