name: Deployment pipeline
on:
  pull_request:
    branches:
      - master
  #Get the secret auth token from Fly.io
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  #Checkout code from git repository in virtaul machine using ubuntu-20.04
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      #Use public action that checkout the code in repository
      - uses: actions/checkout@v3
      #Use public action to setup node in virtual machine in order to use npm commands from package.json
      - uses: actions/setup-node@v3
        #Add parameter to action
        with:
          node-version: '16'
        #Step to install npm dependencies in the enveironment
      - name: npm install
        run: npm install
        #Step to lint the code
      - name: lint
        run: npm run eslint
        #Step to build the code
      - name: build
        run: npm run build
        #Step to test the code
      - name: test
        run: npm run test
      #Step to cypress tests(the app must be running first)
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:3001
      if: github.event.pull_request.merged    
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app
        run: flyctl deploy --remote-only
